package br.com.poc.apppocmongo.pocbradesco;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.ArrayList;
import java.util.List;

import org.junit.Test;
import org.junit.jupiter.api.Order;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import br.com.poc.apppocmongo.model.LastParticipantEntity;
import br.com.poc.apppocmongo.repository.LastParticipantRepository;

@RunWith(SpringRunner.class)
@SpringBootTest
public class MongoDbAutoGenerated {

	@Autowired
	LastParticipantRepository lastParticipantRepository;

	@Test
	public void contextLoads() {
	}

	@Test
	@Order(1)
	public void createLastParticipant() {
		List<LastParticipantEntity> lista = new ArrayList<>();
		LastParticipantEntity lastParticipantEntity = new LastParticipantEntity();
		lastParticipantEntity.setBusinessEntityId(null);
		lastParticipantEntity.setBusinessEntityRel(null);
		lastParticipantEntity.setLoggedUserId("1111111");
		lastParticipantEntity.setLoggedUserRel("CPF");
		lastParticipantEntity.setIspb("SANTANDER");
		lista.add(lastParticipantEntity);
		lastParticipantEntity = new LastParticipantEntity();
		lastParticipantEntity.setBusinessEntityId("2222222");
		lastParticipantEntity.setBusinessEntityRel("CNPJ");
		lastParticipantEntity.setLoggedUserId("1111111");
		lastParticipantEntity.setLoggedUserRel("CPF");
		lastParticipantEntity.setIspb("SANTANDER");
		lista.add(lastParticipantEntity);
		lastParticipantEntity = new LastParticipantEntity();
		lastParticipantEntity.setBusinessEntityId("2222222");
		lastParticipantEntity.setBusinessEntityRel("CNPJ");
		lastParticipantEntity.setLoggedUserId("1111111");
		lastParticipantEntity.setLoggedUserRel("CPF");
		lastParticipantEntity.setIspb("ITAU");
		lista.add(lastParticipantEntity);
		lastParticipantRepository.saveAll(lista);
		assertThat(lastParticipantRepository.findAll().size()).isEqualTo(3);
	}

	@Test
	@Order(2)
	public void findLastParticipantCPF() {
		LastParticipantEntity lastParticipantEntity = new LastParticipantEntity();
		lastParticipantEntity.setBusinessEntityId(null);
		lastParticipantEntity.setBusinessEntityRel(null);
		lastParticipantEntity.setLoggedUserId("1111111");
		lastParticipantEntity.setLoggedUserRel("CPF");
		assertThat(lastParticipantRepository.findByBusinessEntityIdAndBusinessEntityRelAndLoggedUserIdAndLoggedUserRel(
				lastParticipantEntity.getBusinessEntityId(), 
				lastParticipantEntity.getBusinessEntityRel(), 
				lastParticipantEntity.getLoggedUserId(),
				lastParticipantEntity.getLoggedUserRel()
				).size())
				.isEqualTo(1);
	}

	@Test
	@Order(3)
	public void findLastParticipantCPFCNPJ() {
		LastParticipantEntity lastParticipantEntity = new LastParticipantEntity();
		lastParticipantEntity.setBusinessEntityId("2222222");
		lastParticipantEntity.setBusinessEntityRel("CNPJ");
		lastParticipantEntity.setLoggedUserId("1111111");
		lastParticipantEntity.setLoggedUserRel("CPF");
		assertThat(lastParticipantRepository.findByBusinessEntityIdAndBusinessEntityRelAndLoggedUserIdAndLoggedUserRel(
				lastParticipantEntity.getBusinessEntityId(), 
				lastParticipantEntity.getBusinessEntityRel(), 
				lastParticipantEntity.getLoggedUserId(),
				lastParticipantEntity.getLoggedUserRel()
				).size())
				.isEqualTo(2);
	}

}
